"""Make landing points and kde non-nullable

Revision ID: 2cfa56b302d1
Revises: 3b7c916ce163
Create Date: 2023-07-19 11:34:27.084882

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '2cfa56b302d1'
down_revision = '3b7c916ce163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectory_prediction_data', schema=None) as batch_op:
        batch_op.alter_column('landing_points',
               existing_type=Geometry(geometry_type='MULTIPOINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)
        batch_op.alter_column('kde',
               existing_type=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectory_prediction_data', schema=None) as batch_op:
        batch_op.alter_column('kde',
               existing_type=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)
        batch_op.alter_column('landing_points',
               existing_type=Geometry(geometry_type='MULTIPOINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)

    # ### end Alembic commands ###
