"""KDE can have multiple polygons

Revision ID: 3df251028051
Revises: 2cfa56b302d1
Create Date: 2023-07-19 17:12:58.002863

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '3df251028051'
down_revision = '2cfa56b302d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectory_prediction_data', schema=None) as batch_op:
        batch_op.alter_column('kde',
               existing_type=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectory_prediction_data', schema=None) as batch_op:
        batch_op.alter_column('kde',
               existing_type=Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               type_=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               existing_nullable=False)

    # ### end Alembic commands ###
