"""Initial

Revision ID: a8b6a1ec9e22
Revises: 
Create Date: 2023-07-07 16:07:17.121777

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'a8b6a1ec9e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('trajectory_prediction_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_points', Geometry(geometry_type='MULTIPOINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('kde', Geometry(geometry_type='POLYGON', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('bad_landing_areas', Geometry(geometry_type='MULTIPOLYGON', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trajectory_prediction_data', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_trajectory_prediction_data_bad_landing_areas', ['bad_landing_areas'], unique=False, postgresql_using='gist', postgresql_ops={})
        batch_op.create_geospatial_index('idx_trajectory_prediction_data_kde', ['kde'], unique=False, postgresql_using='gist', postgresql_ops={})
        batch_op.create_geospatial_index('idx_trajectory_prediction_data_landing_points', ['landing_points'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectory_prediction_data', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_trajectory_prediction_data_landing_points', postgresql_using='gist', column_name='landing_points')
        batch_op.drop_geospatial_index('idx_trajectory_prediction_data_kde', postgresql_using='gist', column_name='kde')
        batch_op.drop_geospatial_index('idx_trajectory_prediction_data_bad_landing_areas', postgresql_using='gist', column_name='bad_landing_areas')

    op.drop_geospatial_table('trajectory_prediction_data')
    # ### end Alembic commands ###
